# Generated by Django 2.2.12 on 2025-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemID', models.CharField(max_length=20)),
                ('UserID', models.IntegerField(blank=True, null=True)),
                ('EmployeeNumber', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('MiddleInitial', models.CharField(max_length=20)),
                ('ExtensionName', models.CharField(max_length=100)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('BirthDate', models.DateField()),
                ('GenderID', models.CharField(max_length=100)),
                ('DivisionID', models.IntegerField(blank=True, null=True)),
                ('PositionID', models.IntegerField(blank=True, null=True)),
                ('SalaryGradeID', models.IntegerField(blank=True, null=True)),
                ('SalaryStepID', models.IntegerField(blank=True, null=True)),
                ('StatusID', models.IntegerField(blank=True, null=True)),
                ('RemarksStatus', models.TextField(blank=True, null=True)),
                ('TransDate', models.DateTimeField()),
                ('StringID', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'UserBasicInfo',
                'managed': False,
            },
        ),
    ]
