# Generated by Django 2.2.12 on 2025-10-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportphoto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
