# Generated by Django 3.2.16 on 2025-10-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spms', '0002_auto_20251016_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBSPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PerformanceID', models.CharField(max_length=20)),
                ('FiscalYear', models.IntegerField(blank=True, null=True)),
                ('DateStart', models.DateField()),
                ('DateEnds', models.DateField()),
                ('PerformanceDate', models.DateField()),
                ('RatingPeriod', models.IntegerField(blank=True, null=True)),
                ('MFOCommonID', models.IntegerField(blank=True, null=True)),
                ('PerformanceTypeID', models.IntegerField(blank=True, null=True)),
                ('FinalRating', models.DecimalField(decimal_places=3, max_digits=10)),
                ('MotherUnitID', models.IntegerField(blank=True, null=True)),
                ('DivisionUnitID', models.IntegerField(blank=True, null=True)),
                ('PositionID', models.IntegerField(blank=True, null=True)),
                ('RateeID', models.BigIntegerField()),
                ('RateeLastName', models.TextField()),
                ('RateeName', models.TextField()),
                ('RaterID', models.BigIntegerField()),
                ('RaterName', models.TextField()),
                ('ApproverID', models.BigIntegerField()),
                ('ApproverName', models.TextField()),
                ('OfficeHeadID', models.BigIntegerField()),
                ('OfficeHeadName', models.TextField()),
                ('RaterApproverID', models.BigIntegerField()),
                ('EncodedID', models.BigIntegerField()),
                ('CommitmentMessage', models.TextField()),
                ('PerformanceRemarks', models.TextField()),
                ('TransDate', models.DateTimeField()),
                ('StatusID', models.IntegerField(blank=True, null=True)),
                ('StringID', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'CBSPerformance',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PassportPhoto',
        ),
    ]
