# Generated by Django 3.2.16 on 2025-10-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'UtilDesignation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilDivisionSectionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DivisionID', models.IntegerField(blank=True, null=True)),
                ('SectionUnitName', models.CharField(max_length=255)),
                ('CodeName', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'UtilDivisionSectionUnit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilOfficeDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DivisionName', models.CharField(max_length=255)),
                ('CodeName', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'UtilOfficeDivision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilSalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalaryGrade', models.CharField(max_length=50)),
                ('StepOne', models.IntegerField(blank=True, null=True)),
                ('StepTwo', models.IntegerField(blank=True, null=True)),
                ('StepThree', models.IntegerField(blank=True, null=True)),
                ('StepFour', models.IntegerField(blank=True, null=True)),
                ('StepFive', models.IntegerField(blank=True, null=True)),
                ('StepSix', models.IntegerField(blank=True, null=True)),
                ('StepSeven', models.IntegerField(blank=True, null=True)),
                ('StepEight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UtilSalaryGrade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilSalaryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StepName', models.CharField(max_length=50)),
                ('ColoumnName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UtilSalaryStep',
                'managed': False,
            },
        ),
    ]
