# Generated by Django 3.2.16 on 2025-10-09 10:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification_tbl',
            fields=[
                ('Classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('Classification', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('Gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('Gender', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responder_tbl',
            fields=[
                ('Responder_id', models.AutoField(primary_key=True, serialize=False)),
                ('Gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='dbcreate.genders')),
                ('Resp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('Role_id', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Severity_tbl',
            fields=[
                ('Serverity_id', models.AutoField(primary_key=True, serialize=False)),
                ('Severity', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_tbl',
            fields=[
                ('Status_id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TLP_tbl',
            fields=[
                ('TLP_id', models.AutoField(primary_key=True, serialize=False)),
                ('TLP', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_tbl',
            fields=[
                ('Ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ticket_number', models.CharField(blank=True, max_length=255, null=True)),
                ('Score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('Vulnerability', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Recommendations', models.TextField(blank=True, null=True)),
                ('file_reference', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('file_enc', models.CharField(blank=True, max_length=255, null=True)),
                ('Classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_classification', to='dbcreate.classification_tbl')),
                ('Responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_responder', to='dbcreate.responder_tbl')),
                ('Severity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_severity', to='dbcreate.severity_tbl')),
                ('TLP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tlp', to='dbcreate.tlp_tbl')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_by', to='dbcreate.responder_tbl')),
            ],
        ),
        migrations.AddField(
            model_name='responder_tbl',
            name='Roles',
            field=models.ManyToManyField(blank=True, related_name='resroles', to='dbcreate.Roles'),
        ),
        migrations.CreateModel(
            name='IR_tbl',
            fields=[
                ('IR_id', models.AutoField(primary_key=True, serialize=False)),
                ('Actions_taken', models.TextField(blank=True, null=True)),
                ('Impact', models.TextField(blank=True, null=True)),
                ('Root_cause', models.TextField(blank=True, null=True)),
                ('Lessons_learned', models.TextField(blank=True, null=True)),
                ('Status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TStatus', to='dbcreate.status_tbl')),
                ('Ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ticket', to='dbcreate.ticket_tbl')),
            ],
        ),
    ]
