# Generated by Django 3.2.16 on 2025-10-14 08:20

from django.db import migrations, models
import django.db.models.deletion
import core.django_helpers.helpers_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilGender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'UtilGender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtilStatusName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
                ('sample', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UtilStatusName',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationID', models.CharField(max_length=20)),
                ('RequiredID', models.IntegerField(blank=True, null=True)),
                ('AttachedFiles', models.ImageField(upload_to='attached_files/')),
                ('TransDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('brgyCode', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('brgyDesc', models.TextField(blank=True, null=True)),
                ('regCode', models.CharField(blank=True, max_length=255, null=True)),
                ('provCode', models.CharField(default='', max_length=255)),
                ('citymunCode', models.CharField(blank=True, max_length=255, null=True)),
                ('DefaultLogo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'UtilRefBarangay',
            },
        ),
        migrations.CreateModel(
            name='CityMun',
            fields=[
                ('psgcCode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('citymunDesc', models.TextField()),
                ('regDesc', models.CharField(max_length=255)),
                ('provCode', models.CharField(max_length=255)),
                ('citymunCode', models.CharField(max_length=255)),
                ('DefaultLogo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'UtilRefCityMun',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=255)),
                ('NiceName', models.CharField(max_length=255)),
                ('numcode', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'UtilRefCountry',
            },
        ),
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('UserID', models.CharField(max_length=50)),
                ('TransactionID', models.CharField(max_length=50)),
                ('UriSegmentLoc', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('log', models.TextField()),
                ('TransDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs_error',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('psgcCode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('provDesc', models.TextField()),
                ('regCode', models.CharField(max_length=255)),
                ('provCode', models.CharField(max_length=255)),
                ('DefaultLogo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'UtilRefProvince',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ClassID', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationID', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('ExtensionName', models.CharField(max_length=100)),
                ('GenderID', models.CharField(max_length=100)),
                ('NationalityID', models.IntegerField(blank=True, null=True)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('TaxIDNumber', models.CharField(blank=True, max_length=50)),
                ('OrgAgencyCompany', models.CharField(blank=True, max_length=200)),
                ('OrgUnitDeptDiv', models.CharField(blank=True, max_length=200)),
                ('HouseUnitNumber', models.CharField(blank=True, max_length=200)),
                ('Street', models.CharField(blank=True, max_length=200)),
                ('Barangay', models.CharField(blank=True, max_length=50)),
                ('MunicipalityCity', models.CharField(blank=True, max_length=50)),
                ('ProvinceState', models.CharField(blank=True, max_length=50)),
                ('ZipCode', models.CharField(blank=True, max_length=5)),
                ('MobileNumber', models.CharField(blank=True, max_length=50)),
                ('EmailAddress', models.CharField(blank=True, max_length=100)),
                ('PassportPhoto', models.ImageField(blank=True, null=True, upload_to='passport_photos/', validators=[core.django_helpers.helpers_file.validate_file_extension])),
                ('SignatureImage', models.ImageField(blank=True, null=True, upload_to='signatures/', validators=[core.django_helpers.helpers_file.validate_file_extension])),
                ('TermServiceID', models.IntegerField(blank=True, null=True)),
                ('ApproveDate', models.DateTimeField(blank=True, null=True)),
                ('TransDate', models.DateTimeField()),
                ('StringID', models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, unique=True)),
                ('StatusID', models.ForeignKey(db_column='StatusID', on_delete=django.db.models.deletion.CASCADE, to='pnpki.utilstatusname')),
            ],
        ),
    ]
