# Generated by Django 2.2.12 on 2025-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnpki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
                ('RangeStarts', models.CharField(max_length=10)),
                ('RangeEnds', models.CharField(max_length=10)),
                ('StartsDate', models.CharField(max_length=6)),
                ('EndsDate', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'UtilFrequencyClass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('QuartID', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('StartsDate', models.DateTimeField()),
                ('EndsDate', models.DateTimeField()),
                ('TransDate', models.DateTimeField()),
                ('StatusID', models.IntegerField()),
                ('StringID', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'QuarterlyReport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ReportID', models.CharField(max_length=20)),
                ('BatchNumber', models.CharField(max_length=100)),
                ('DateStarts', models.DateField()),
                ('DateEnds', models.DateField()),
                ('SubmittedDate', models.DateField()),
                ('ReportRemarks', models.TextField(blank=True, null=True)),
                ('StatusID', models.IntegerField()),
                ('TransDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'SummaryReport',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='requireddocs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='utilstatusname',
            options={},
        ),
    ]
