# Generated by Django 3.2.16 on 2025-10-24 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pnpki', '0002_auto_20251021_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilstatusname',
            name='sample',
        ),
        migrations.AddField(
            model_name='utilstatusname',
            name='ClassName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilstatusname',
            name='StatusCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='application',
            table='Application',
        ),
        migrations.AlterModelTable(
            name='attachment',
            table='Attachment',
        ),
        migrations.AlterModelTable(
            name='requireddocs',
            table='UtilRequiredDocs',
        ),
    ]
